Fixture/update config files
dial-once/node-logtify pull request #29
Opened 2018-08-19 12:47 UTC by steven-heng

Npm audit found 0 vulnerabilities
Modify rules command of package.json and Makefile

2018-08-20 13:23 UTC, jkernech requested changes

2018-08-20 13:23 UTC, jkernech commented on Makefile
> +	@sonar-scanner-2.8/bin/sonar-runner -e -Dsonar.analysis.mode=publish -Dsonar.host.url=$(SONAR_HOST_URL) -Dsonar.login=$(SONAR_LOGIN) -Dsonar.password=$(SONAR_PASS)
Revert your changes here, `sonar-runner` is deprecated so you need to use `sonar-scanner`

2018-09-04 13:15 UTC, jkernech approved these changes

2018-09-04 13:16 UTC, jkernech requested changes
Tests have to be fixed

2018-10-15 04:24 UTC, dialonce commented on src/modules/message.js
>  function jsonify(obj) {
![CRITICAL](https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL') Refactor this function to reduce its Cognitive Complexity from 16 to the 15 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.dialonce.net/coding_rules#rule_key=javascript%3AS3776)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Refactor this function to always return the same type. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.dialonce.net/coding_rules#rule_key=javascript%3AS3800)

2018-10-15 04:24 UTC, dialonce commented on src/modules/message.js
>    getPrefix(settings = {}, delimiter = ':') {
![CRITICAL](https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL') Refactor this function to reduce its Cognitive Complexity from 18 to the 15 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.dialonce.net/coding_rules#rule_key=javascript%3AS3776)

2018-10-15 04:24 UTC, dialonce commented on src/subscribers/console-link.js
>    handle(message) {
![CRITICAL](https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL') Refactor this function to reduce its Cognitive Complexity from 19 to the 15 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.dialonce.net/coding_rules#rule_key=javascript%3AS3776)

2018-10-15 04:40 UTC, dialonce commented
SonarQube analysis reported 5 issues
* ![CRITICAL][CRITICAL] 4 critical
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [index.js#L175](https://github.com/dial-once/node-logtify/blob/b2e4446a5e3296039be740979be314ebb95114b8/src/index.js#L175): Refactor this function to reduce its Cognitive Complexity from 16 to the 15 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.dialonce.net/coding_rules#rule_key=javascript%3AS3776)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2018-10-20 10:52 UTC, merged